# permissions for end users to view uniteddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uniteddeployment-viewer-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - uniteddeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - uniteddeployments/status
  verbs:
  - get
