# permissions for end users to edit uniteddeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uniteddeployment-editor-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - uniteddeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - uniteddeployments/status
  verbs:
  - get
