apiVersion: v1
kind: ServiceAccount
metadata:
  name: yurt-tunnel-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yurt-tunnel-agent
subjects:
  - kind: ServiceAccount
    name: yurt-tunnel-agent
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: yurt-tunnel-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: yurt-tunnel-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - create 
  - list
  - watch
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: yurt-tunnel-agent
  name: yurt-tunnel-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: yurt-tunnel-agent
  template:
    metadata:
      labels:
        k8s-app: yurt-tunnel-agent
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        openyurt.io/is-edge-worker: "true"
      containers:
      - command:
        - yurt-tunnel-agent
        args:
        - --node-name=$(NODE_NAME)
        - --node-ip=$(POD_IP)
        - --apiserver-addr=__kubernetes_service_host__:__kubernetes_service_port_https__
        - --v=2
        image: openyurt/yurt-tunnel-agent:latest
        imagePullPolicy: IfNotPresent
        name: yurt-tunnel-agent
        volumeMounts:
        - name: k8s-dir
          mountPath: /etc/kubernetes
        - name: kubelet-pki
          mountPath: /var/lib/kubelet/pki
        - name: tunnel-agent-dir
          mountPath: /var/lib/yurttunnel-agent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: yurt-tunnel-agent
      tolerations:
        - operator: Exists
      volumes:
      - name: k8s-dir
        hostPath:
          path: /etc/kubernetes
          type: Directory
      - name: kubelet-pki
        hostPath:
          path: /var/lib/kubelet/pki
          type: Directory
      - name: tunnel-agent-dir
        hostPath:
          path: /var/lib/yurttunnel-agent
          type: DirectoryOrCreate
