apiVersion: apps.openyurt.io/v1alpha1
kind: UnitedDeployment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ud-statefulset
spec:
  revisionHistoryLimit: 5 
  selector:
    matchLabels:
      app: ud-statefulset
  workloadTemplate:
    statefulSetTemplate:
      metadata:
        labels:
          app: ud-statefulset
      spec:
        template:
          metadata:
            labels:
              app: ud-statefulset
          spec:
            containers:
              - name: nginx
                image: nginx:1.19.3
  topology:
    pools:
    - name: cloud
      nodeSelectorTerm:
        matchExpressions:
        - key: openyurt.io/uniteddeployment
          operator: In
          values:
          - cloud
      replicas: 2
    - name: edge
      nodeSelectorTerm:
        matchExpressions:
        - key: openyurt.io/uniteddeployment
          operator: In
          values:
          - edge
      replicas: 1
      tolerations:
      - effect: NoSchedule
        key: openyurt.io/taints
        operator: Exists
