apiVersion: apps.openyurt.io/v1alpha1
kind: UnitedDeployment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ud-deployment
spec:
  selector:
    matchLabels:
      app: ud-deployment
  workloadTemplate:
    deploymentTemplate:
      metadata:
        labels:
          app: ud-deployment
      spec:
        template:
          metadata:
            labels:
              app: ud-deployment
          spec:
            containers:
              - name: nginx
                image: nginx:1.19.3
  topology:
    pools:
    - name: cloud 
      nodeSelectorTerm:
        matchExpressions:
        - key: openyurt.io/uniteddeployment
          operator: In
          values:
          - cloud 
      replicas: 2 
    - name: edge 
      nodeSelectorTerm:
        matchExpressions:
        - key: openyurt.io/uniteddeployment
          operator: In
          values:
          - edge 
      replicas: 1
      tolerations:
      - effect: NoSchedule
        key: openyurt.io/taints
        operator: Exists
  revisionHistoryLimit: 5 
